---
- name: install nfs provisioner
  hosts: master
  become: yes
  gather_facts: yes

  tasks:
    - name: check the servers' os version
      when: >
        (ansible_distribution != 'Ubuntu')

        or

        (ansible_distribution_version != '20.04')
      meta: end_play

    - name: setup master node
      when:
        - admin is not defined
        - nfs_ip is not defined
        - nfs_path is not defined
      meta: end_play

    - name: add nfs helm repository
      kubernetes.core.helm_repository:
        name: nfs-subdir-external-provisioner
        repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      register: output

    - name: update helm repo
      shell: helm repo update
      register: output

    - name: install gpu operator
      shell: |
        helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
        --set nfs.server={{ nfs_ip }} \
        --set nfs.path={{ nfs_path }}
      register: output

    - name: set nfs-client as default storage class
      shell: |
        kubectl patch storageclass nfs-client -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
      register: output
