- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: swapoff -a
  register: output

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  register: output

# reference : https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/

- name: prevent package auto upgrade
  replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: 'APT::Periodic::Update-Package-Lists "1";'
    replace: 'APT::Periodic::Update-Package-Lists "0";'
  register: output

- name: install basic packages
  apt:
    pkg:
      - net-tools
      - nfs-common
      - tmux
    state: present
  register: output

- name: disable ufw
  ufw:
    state: disabled
  register: output

- name: stop ufw
  service:
    name: ufw
    state: stopped
    enabled: false
  register: output

- name: copy docker installation script to master
  become_user: "{{ master_user }}"
  copy:
    src: ../files/install_docker_ubuntu.sh
    dest: $HOME
    mode: 0777
  register: output

- name: execute docker installation script
  command: "/home/{{ master_user }}/install_docker_ubuntu.sh"
  register: output

- name: copy daemon.json to master
  copy:
    src: ../files/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  register: output

- name: check if /etc/systemd/system/docker.service.d exists
  stat:
    path: /etc/systemd/system/docker.service.d
  register: stat_result

- name: create /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: not stat_result.stat.exists
  register: output

- name: restart docker daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  register: output

- name: check if /etc/modules-load.d/k8s.conf exists
  stat:
    path: /etc/modules-load.d/k8s.conf
  register: stat_result

- name: create /etc/modules-load.d/k8s.conf
  file:
    path: /etc/modules-load.d/k8s.conf
    state: touch
  when: not stat_result.stat.exists
  register: output

- name: letting iptables see bridged traffic (1)
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: br_netfilter
  register: output

- name: check if /etc/sysctl.d/k8s.conf exists
  stat:
    path: /etc/sysctl.d/k8s.conf
  register: stat_result

- name: create /etc/sysctl.d/k8s.conf
  file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
  when: not stat_result.stat.exists
  register: output

- name: letting iptables see bridged traffic (2)
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  register: output

- name: reload system kernel params
  command: sysctl --system
  register: output

- name: download k8s apt-key.gpg
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    mode: 0644
  register: output

- name: check if /etc/apt/sources.list.d/kubernetes.list exists
  stat:
    path: /etc/apt/sources.list.d/kubernetes.list
  register: stat_result

- name: create /etc/apt/sources.list.d/kubernetes.list
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: touch
  when: not stat_result.stat.exists
  register: output

- name: add k8s package repository
  blockinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    block: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
  register: output

- name: install kubelet / kubeadm / kubectl
  apt:
    pkg:
      - kubelet=1.20.11-00
      - kubeadm=1.20.11-00
      - kubectl=1.20.11-00
    state: present
    update_cache: yes
  register: output

- name: apt-mark hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold
  register: output

- name: apt-mark hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold
  register: output

- name: apt-mark hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold
  register: output

- name: check if k8s script exists (1)
  stat:
    path: "/home/{{ master_user }}/k8s_log.sh"
  register: stat_result

- name: create k8s installation scripts (1)
  file:
    path: "/home/{{ master_user }}/k8s_log.sh"
    state: touch
    mode: 0777
  when: not stat_result.stat.exists
  register: output

- name: check if k8s script exists (2)
  stat:
    path: "/home/{{ master_user }}/k8s_join_master.sh"
  register: stat_result

- name: create k8s installation scripts (2)
  file:
    path: "/home/{{ master_user }}/k8s_join_master.sh"
    state: touch
    mode: 0777
  register: output

- name: check if k8s script exists (3)
  stat:
    path: "/home/{{ master_user }}/k8s_join_worker.sh"
  register: stat_result

- name: create k8s installation scripts (3)
  file:
    path: "/home/{{ master_user }}/k8s_join_worker.sh"
    state: touch
    mode: 0777
  register: output

#- name: kubeadm init
#  shell: "kubeadm init --control-plane-endpoint {{ master_ip }}:6443 --upload-certs --pod-network-cidr \"10.244.0.0/16\" >> /home/{{ master_user }}/k8s_log.sh"
#  register: output

- name: add join master command in its script (1)
  shell: "echo \"#!/bin/bash\" > /home/{{ master_user }}/k8s_join_master.sh"
  register: output

- name: add join master command in its script (2)
  shell: "sed -n \'/kubeadm join/,/control/p\' /home/{{ master_user }}/k8s_log.sh | head -n 3 >> /home/{{ master_user }}/k8s_join_master.sh"
  register: output

- name: add join worker command in its script (1)
  shell: "echo \"#!/bin/bash\" > /home/{{ master_user }}/k8s_join_worker.sh"
  register: output

- name: add join worker command in its script (2)
  shell: "sed -n \'/kubeadm join/,/control/p\' /home/{{ master_user }}/k8s_log.sh | tail -n 2 >> /home/{{ master_user }}/k8s_join_worker.sh"
  register: output

- name: check if master root's $home/.kube exists
  stat:
    path: $HOME/.kube
  register: stat_result

- name: create master root's $home/.kube directory
  file:
    path: $HOME/.kube
    state: directory
  when: not stat_result.stat.exists
  register: output

- name: check if master admin's $home/.kube exists
  become_user: "{{ master_user }}"
  stat:
    path: $HOME/.kube
  register: stat_result

- name: create master admin's $home/.kube directory
  become_user: "{{ master_user }}"
  file:
    path: $HOME/.kube
    state: directory
  when: not stat_result.stat.exists
  register: output

- name: copy /etc/kubernetes/admin.conf as master root's $HOME.kube/config and change owner
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    owner: root
    group: root
    remote_src: yes
  register: output

- name: copy /etc/kubernetes/admin.conf as master admin's $HOME.kube/config and change owner
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ master_user }}/.kube/config"
    owner: "{{ master_user }}"
    group: "{{ master_user }}"
    remote_src: yes
  register: output

- name: enable kubectl auto completion for root
  blockinfile:
    path: $HOME/.bashrc
    block: |
      source <(kubectl completion bash)
      source <(kubeadm completion bash)
  register: output

- name: enable kubectl auto completion for admin
  become_user: "{{ master_user }}"
  blockinfile:
    path: $HOME/.bashrc
    block: |
      source <(kubectl completion bash)
      source <(kubeadm completion bash)
  register: output

#- name: install flannel
#  become: yes
#  become_user: root
#  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
#  args:
#    chdir: "/home/{{ master_user }}"
#  register: output

- name: download helm installation script
  become_user: "{{ master_user }}"
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: $HOME/get_helm.sh
    mode: 0777
  register: output

- name: install helm
  shell: "/home/{{ master_user }}/get_helm.sh"
  register: output
